services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: cine-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Sagas123
      MYSQL_DATABASE: dbcinema
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cine-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pSagas123"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Node.js
  backend:
    build:
      context: ./cinema-backend
      dockerfile: Dockerfile
    container_name: cine-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Sagas123
      DB_NAME: dbcinema
      NODE_ENV: production
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cine-network

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
    container_name: cine-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cine-network

# Red personalizada
networks:
  cine-network:
    driver: bridge

# Volumen para persistir datos de MySQL
volumes:
  mysql_data:
